version: "3"

services:
  broker-service:
    build:
      context: ./broker-service
      # dockerfile: ./broker-service/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1

networks:
  default:
    driver: bridge
